project:
  type: website

website:
  favicon: "img/favicon_io/favicon.ico"
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sql.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



